
trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
- script: echo k8s terraform azure!
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'azure_rsa.pub'

- task: Bash@3
  displayName: Terraform Init/Plan/Apply
  inputs:
    targetType: inline
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    script: |
      set -e

      echo "Terraform version:"
      terraform version

      echo "Initializing Terraform backend..."

      terraform init \
        -backend-config="resource_group_name=dockerkubernetesadam" \
        -backend-config="storage_account_name=storagedockerkubernetesadam" \
        -backend-config="container_name=storagecontainerdockerkubernetesadam" \
        -backend-config="key=kubernetes-dev.tfstate" \
        -backend-config="use_azuread_auth=true"

      echo "Validating..."
      terraform validate

      echo "Planning..."
      terraform plan \
        -var "client_id=$(client_id)" \
        -var "client_secret=$(client_secret)" \
        -var "ssh_public_key=$(ssh_public_key)" \
        -out=tfplan
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'azure_rsa.pub'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'azure-resource-service-connection'
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmStorageAccountName: 'storageaccountadammouldxyz'
    backendAzureRmContainerName: 'storageaccountadammouldcontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
  displayName: 'Run a one-line script'
